# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87dfa47fbe26400c2907cc15d9c34168f4bb81d622e930c6c4f31fd4e5b721bfd695114222a005f970e2e1d924b922287fbf1cbcaa162ee159f5a9b8a5fdbeaf

test:
  secret_key_base: a0ba609ecfe800a27a429a7480857dba070de59bef79f443d89357ecb1e00458d46ee748f2e76613f5dd8d9ad4905f4d652bc57f6830a9a074898fb8ba32d208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
